set_property OFFCHIP_TERM NONE [get_ports output]
set_property CONFIG_VOLTAGE 3.3 [current_design]
set_property CFGBVS VCCO [current_design]
set_property PACKAGE_PIN P20 [get_ports input]
set_property PACKAGE_PIN K17 [get_ports output]
set_property PACKAGE_PIN H4 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports input]
set_property IOSTANDARD LVCMOS33 [get_ports output]
